### ISSUE TITLE
Traefik dosen't applay TLS certificates

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [YevheniiVolosiuk/spin-template-wordpress-basic#1]
HTTPS doesn't work, the browser shows a warning

![image](https://github.com/user-attachments/assets/59681155-410f-428f-9208-280d99fc35fe)

@jaydrogers

Can you look at it when you have time?
It uses the same concept as in spin-laravel-template-basic.

**Comment by jaydrogers** [comment]
Does your Firefox install trust the SSU CA? https://serversideup.net/ca/

**Comment by YevheniiVolosiuk** [comment]
> Does your Firefox install trust the SSU CA? https://serversideup.net/ca/

Thanks for knowing about this CA I thought it was a standard-generated public CA.

It works.
